/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { DEXContractContract } from "./DEXContract";
import { IERC20Contract } from "./IERC20";
import { MigrationsContract } from "./Migrations";
import { MTAContract } from "./MTA";
import { MTBContract } from "./MTB";
import { MTCContract } from "./MTC";
import { MTDContract } from "./MTD";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "DEXContract"): DEXContractContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "MTA"): MTAContract;
      require(name: "MTB"): MTBContract;
      require(name: "MTC"): MTCContract;
      require(name: "MTD"): MTDContract;
    }
  }
}

export { DEXContractContract, DEXContractInstance } from "./DEXContract";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { MTAContract, MTAInstance } from "./MTA";
export { MTBContract, MTBInstance } from "./MTB";
export { MTCContract, MTCInstance } from "./MTC";
export { MTDContract, MTDInstance } from "./MTD";
